name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Specify the operating system for the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12  # Set the Python version for the job

    - name: Install dependencies
      run: |
        python -m venv venv         # Create a virtual environment
        source venv/bin/activate    # Activate the virtual environment
        pip install --upgrade pip   # Ensure pip is up to date
        pip install -r requirements.txt  # Install dependencies from requirements.txt

    - name: Run tests
      run: |
        source venv/bin/activate    # Ensure the virtual environment is activated
        pytest                      # Run the tests using pytest or your preferred testing tool


  deploy:
    name: Deploy to Netlify
    needs: test  
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Install Netlify CLI
      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Step 3: Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          netlify deploy --dir=static --prod --auth=$NETLIFY_AUTH_TOKEN

        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
